# Tests for `trfl` ops using TF2.
# Placeholder for internal Python version compatibility macro.

# Apache 2.0 License
licenses(["notice"])

package(default_visibility = ["//visibility:public"])

py_test(
    name = "action_value_ops_test",
    srcs = ["action_value_ops_test.py"],
    deps = [
        # tensorflow dep,
        "//trfl:action_value_ops",
    ],
)
